version: "3.0"
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: esl
      POSTGRES_USER: esl
      POSTGRES_DB: esl
    ports:
      - 5432:5432
