version: "3.0"
services:
    server:
        network_mode: host
        build:
            context: ./server
            dockerfile: ./Dockerfile
        ports:
            - ${API_PORT}:${API_PORT}
        environment:
            PORT: ${API_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PORT: ${MYSQL_PORT}
            STEAM_API_KEY: ${STEAM_API_KEY}
