version: "3.0"
services:
  mysql:
    image: mysql:5.5
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      PORT: ${FRONTEND_PORT}
      API_URL: http://server:${API_PORT}
      NODE_ENV: ${NODE_ENV}
  
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      PORT: ${API_PORT}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - mysql
      - redis
volumes:
  mysql_volume:
