version: "3.0"
services:
  web:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_PATH: /v2
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      PORT: ${FRONTEND_PORT}
      API_URL: http://localhost:${API_PORT}
      NODE_ENV: ${NODE_ENV}
      BASE_PATH: /v2
  
  server:
    network_mode: host
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      PORT: ${API_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PORT: ${MYSQL_PORT}
