version: "3.0"
services:
  mysql:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: esl
      MYSQL_PASSWORD: esl
      MYSQL_DATABASE: esl
      MYSQL_USER: esl-user
    ports:
      - 3306:3306
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: esl
      POSTGRES_USER: esl
      POSTGRES_DB: esl
    ports:
      - 5432:5432
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MYSQL_HOST: host.docker.internal
      MYSQL_DATABASE: esl
      MYSQL_USERNAME: esl-user
      MYSQL_PASSWORD: esl
      MYSQL_PORT: 3306
      BASE_PATH:
      API_URL: http://localhost
  
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      MYSQL_HOST: host.docker.internal
      MYSQL_DATABASE: esl
      MYSQL_USERNAME: esl-user
      MYSQL_PASSWORD: esl
      MYSQL_PORT: 3306
      BASE_PATH:
      API_URL: http://localhost

